### ISSUE TITLE
Hi! Where is utils and plotting?

### ISSUE THREAD

**Issue by KKopilka** [LoboaTeresa/AI-Trainer#1]

**Comment by LoboaTeresa** [comment]
Hi @KKopilka , everything you need is inside the ai_trainer package folder. 

Plotting utils --> ai_trainer /drawing.py

Hope it helps. 
Cheers!

**Comment by KKopilka** [comment]
Hi @LoboaTeresa thanks for the answer! But if I run this command, I get this error
python main.py --input_video sqaut.mp4     
Traceback (most recent call last):
  File "D:\AI-Trainer\main.py", line 8, in <module>
    from ai_trainer.models import BlazePoseModel
  File "D:\AI-Trainer\ai_trainer\__init__.py", line 3, in <module>
    from . import models
  File "D:\AI-Trainer\ai_trainer\models.py", line 11, in <module> 
    from . import utils
ImportError: cannot import name 'utils' from partially initialized module 'ai_trainer' (most likely due to a circular import) (D:\AI-Trainer\ai_trainer\__init__.py)
